begin;
select plan(40);

select has_table('private', 'device_auth_key_rotation_receipts', 'rotation receipt tombstone table exists');
select has_column('private', 'device_auth_key_bindings', 'binding_revision', 'active key binding revision exists');
select has_column('private', 'device_auth_key_bindings', 'rotation_lineage_digest', 'rotation lineage digest exists');
select has_column('private', 'device_auth_token_families', 'key_binding_revision', 'token family binding revision exists');
select has_column('private', 'device_auth_access_tokens', 'key_thumbprint', 'access proof binding thumbprint exists');
select has_column('private', 'device_auth_access_tokens', 'key_binding_revision', 'access proof binding revision exists');

select ok((select relrowsecurity and relforcerowsecurity from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid = c.relnamespace where n.nspname = 'private' and c.relname = 'device_auth_key_rotation_receipts'), 'rotation receipts enable and force RLS');
select has_function('api', 'device_auth_rotate_key_v1', array['text','text','text','text','text','text','text','text','text','text','text','text','text','text','text','integer'], 'rotation RPC has exact closed signature');
select function_owner_is('api','device_auth_rotate_key_v1',array['text','text','text','text','text','text','text','text','text','text','text','text','text','text','text','integer'],'skillmap_device_auth_definer','rotation RPC has dedicated definer owner');
select ok(not has_function_privilege('public','api.device_auth_rotate_key_v1(text,text,text,text,text,text,text,text,text,text,text,text,text,text,text,integer)','execute'), 'rotation RPC is not executable by public');
select ok(not has_function_privilege('anon','api.device_auth_rotate_key_v1(text,text,text,text,text,text,text,text,text,text,text,text,text,text,text,integer)','execute'), 'rotation RPC is not executable by anon');
select ok(not has_function_privilege('authenticated','api.device_auth_rotate_key_v1(text,text,text,text,text,text,text,text,text,text,text,text,text,text,text,integer)','execute'), 'rotation RPC is not executable by authenticated');
select ok(not has_function_privilege('service_role','api.device_auth_rotate_key_v1(text,text,text,text,text,text,text,text,text,text,text,text,text,text,text,integer)','execute'), 'rotation RPC is not executable by service_role while feature is off');

select results_eq($$select count(*)::int from pg_catalog.pg_policies where schemaname = 'private' and tablename = 'device_auth_key_rotation_receipts' and roles @> array['skillmap_device_auth_definer'::name]$$, $$select 2$$, 'definer has separate rotation receipt read and insert policies');
select ok((select exists (select 1 from pg_catalog.pg_indexes where schemaname = 'private' and indexname = 'device_auth_key_bindings_one_active_per_device')), 'one active key partial unique index remains in force');
select ok((select count(*) from pg_catalog.pg_constraint where conname = 'device_auth_key_rotation_receipts_response_check') = 1, 'receipt response is a closed non-secret schema');
select ok((select count(*) from pg_catalog.pg_constraint where conname = 'device_auth_key_rotation_receipts_suite_check') = 1, 'receipts remain P-256 only');
select ok((select count(*) from pg_catalog.pg_constraint where conname = 'device_auth_key_rotation_receipts_idempotency_check') = 1, 'receipt idempotency key has exact grammar');
select ok((select count(*) from pg_catalog.pg_constraint where conname = 'device_auth_key_rotation_receipts_request_check') = 1, 'receipt request digest has exact grammar');
select ok((select count(*) from pg_catalog.pg_constraint where conname = 'device_auth_key_bindings_revision_check') = 1, 'binding revision is positive');
select ok((select count(*) from pg_catalog.pg_constraint where conname = 'device_auth_key_bindings_lineage_check') = 1, 'lineage digest is bounded');
select ok((select count(*) from pg_catalog.pg_attribute a join pg_catalog.pg_class c on c.oid = a.attrelid join pg_catalog.pg_namespace n on n.oid = c.relnamespace where n.nspname = 'private' and c.relname = 'device_auth_key_rotation_receipts' and a.attname in ('idempotency_key_digest','idempotency_key_version') and not a.attisdropped) = 2, 'rotation receipts persist only versioned idempotency digest material');
select ok((select lower(pg_get_functiondef('api.device_auth_rotate_key_v1(text,text,text,text,text,text,text,text,text,text,text,text,text,text,text,integer)'::regprocedure)) like '%set search_path to ''''%' ), 'rotation RPC pins empty search_path');
select ok((select pg_get_functiondef('api.device_auth_rotate_key_v1(text,text,text,text,text,text,text,text,text,text,text,text,text,text,text,integer)'::regprocedure) like '%for update%' ), 'rotation RPC uses row locks');
select ok((select pg_get_functiondef('api.device_auth_rotate_key_v1(text,text,text,text,text,text,text,text,text,text,text,text,text,text,text,integer)'::regprocedure) like '%rotate-old%' and pg_get_functiondef('api.device_auth_rotate_key_v1(text,text,text,text,text,text,text,text,text,text,text,text,text,text,text,integer)'::regprocedure) like '%rotate-new%' ), 'rotation RPC requires both closed proof purposes');
select ok((select pg_get_functiondef('api.device_auth_rotate_key_v1(text,text,text,text,text,text,text,text,text,text,text,text,text,text,text,integer)'::regprocedure) like '%idempotency_conflict%' ), 'rotation RPC preserves changed-digest conflict');
select has_function('api', 'device_auth_get_rotation_receipt_v1', array['text','text','integer','text'], 'receipt replay RPC has exact closed signature');
select function_owner_is('api','device_auth_get_rotation_receipt_v1',array['text','text','integer','text'],'skillmap_device_auth_definer','receipt replay RPC has dedicated definer owner');
select ok(not has_function_privilege('public','api.device_auth_get_rotation_receipt_v1(text,text,integer,text)','execute'), 'receipt replay RPC is not executable by public');
select ok((select pg_get_functiondef('api.device_auth_rotate_key_v1(text,text,text,text,text,text,text,text,text,text,text,text,text,text,text,integer)'::regprocedure) like '%device-auth-initiate:%'), 'rotation takes the exact M3.03 initiation advisory lock');
select ok((select pg_get_functiondef('api.device_auth_rotate_key_v1(text,text,text,text,text,text,text,text,text,text,text,text,text,text,text,integer)'::regprocedure) like '%order by f.family_id%'), 'rotation locks families in deterministic order before device');
select ok((select strpos(pg_get_functiondef('api.device_auth_rotate_key_v1(text,text,text,text,text,text,text,text,text,text,text,text,text,text,text,integer)'::regprocedure), 'select * into v_device') < strpos(pg_get_functiondef('api.device_auth_rotate_key_v1(text,text,text,text,text,text,text,text,text,text,text,text,text,text,text,integer)'::regprocedure), 'select * into v_active')), 'rotation lock order is family then device then active key');
select ok((select pg_get_functiondef('api.device_auth_rotate_key_v1(text,text,text,text,text,text,text,text,text,text,text,text,text,text,text,integer)'::regprocedure) like '%v_invalid_active_family%' and pg_get_functiondef('api.device_auth_rotate_key_v1(text,text,text,text,text,text,text,text,text,text,text,text,text,text,text,integer)'::regprocedure) like '%idle_expires_at%' and pg_get_functiondef('api.device_auth_rotate_key_v1(text,text,text,text,text,text,text,text,text,text,text,text,text,text,text,integer)'::regprocedure) like '%absolute_expires_at%'), 'rotation fails closed for revoked, idle-expired, or absolute-expired live families');
select ok((select pg_get_functiondef('api.device_auth_rotate_key_v1(text,text,text,text,text,text,text,text,text,text,text,text,text,text,text,integer)'::regprocedure) like '%v_selected_family.key_binding_revision%' and pg_get_functiondef('api.device_auth_rotate_key_v1(text,text,text,text,text,text,text,text,text,text,text,text,text,text,text,integer)'::regprocedure) like '%v_selected_family.current_generation%'), 'rotation fails closed when family revision or generation is stale');
select ok((select pg_get_functiondef('api.device_auth_rotate_key_v1(text,text,text,text,text,text,text,text,text,text,text,text,text,text,text,integer)'::regprocedure) like '%v_selected_family.key_thumbprint is distinct from v_active.key_thumbprint%' and pg_get_functiondef('api.device_auth_rotate_key_v1(text,text,text,text,text,text,text,text,text,text,text,text,text,text,text,integer)'::regprocedure) like '%v_selected_family.proof_suite is distinct from v_active.proof_suite%'), 'rotation fails closed when family thumbprint or suite crosses the active binding');
select ok((select pg_get_functiondef('api.device_auth_rotate_key_v1(text,text,text,text,text,text,text,text,text,text,text,text,text,text,text,integer)'::regprocedure) like '%pairing_id = v_selected_family.pairing_id%' and pg_get_functiondef('api.device_auth_rotate_key_v1(text,text,text,text,text,text,text,text,text,text,text,text,text,text,text,integer)'::regprocedure) like '%key_thumbprint = v_active.key_thumbprint%'), 'pairing invalidation is restricted to the exact old-key lineage');
select ok((select pg_get_functiondef('api.device_auth_get_rotation_receipt_v1(text,text,integer,text)'::regprocedure) like '%v_device.state%' and pg_get_functiondef('api.device_auth_get_rotation_receipt_v1(text,text,integer,text)'::regprocedure) like '%v_active_family_count%'), 'receipt replay rechecks live device and exact-one lineage before returning');
select ok(not has_schema_privilege('skillmap_device_auth_definer','private','create') and not has_schema_privilege('skillmap_device_auth_definer','api','create'), 'definer retains no persistent schema CREATE privilege');
select is((select api.device_auth_rotate_key_v1(null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null)->>'error'), 'invalid_request', 'malformed rotation input is rejected before any state change');
select is((select api.device_auth_get_rotation_receipt_v1(null,null,null,null)->>'error'), 'invalid_request', 'malformed receipt lookup input is rejected');

select * from finish();
rollback;
