import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  globalIgnores([
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Contract and schema artifacts are generated by scripts/generate-contracts.mjs
    // and are not hand-authored; linting the emitted single-line payloads adds noise
    // and breaks the lint gate. They are validated by the generation --check instead.
    "lib/contracts/generated/**",
    // Build/deploy output emitted by `next build` / OpenNext; never hand-authored.
    ".open-next/**",
    ".wrangler/**"
  ])
]);

export default eslintConfig;
